name: "Test - E2E Example apps"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

jobs:
  test-example-apps:
    name: Test Example Apps
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        example:
          - ask-the-documents

    steps:
      - run: pwd

      - run: df -h

      - uses: "actions/checkout@v6"

      - run: df -h

      - uses: ./.github/actions/setup-haskell
        with:
          cabal-project-dir: waspc

      - run: df -h

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - run: df -h

      - name: Install Wasp CLI
        working-directory: waspc
        run: ./run install

      - run: df -h
