name: "Check - Formatting"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: .nvmrc

      - name: Run Prettier
        run: |
          npm ci
          npm run prettier:check

  ormolu:
    runs-on: ubuntu-latest

    steps:
      - run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - uses: actions/checkout@v6

      - name: Parse oromolu version
        working-directory: waspc
        run: |
          echo "ORMOLU_VERSION=$(grep 'ormolu ==' dev-tool.project | sed 's/.*==\s*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV

      # `run-ormolu` versions > 15 require ormolu version >= 0.7.5.0
      - uses: haskell-actions/run-ormolu@v15
        with:
          version: ${{ env.ORMOLU_VERSION }}

  cabal-gild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Parse cabal-gild version
        working-directory: waspc
        run: |
          echo "CABAL_GILD_VERSION=$(grep 'cabal-gild ==' dev-tool.project | sed 's/.*==\s*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV

      - uses: tfausak/cabal-gild-setup-action@v2
        with:
          version: ${{ env.CABAL_GILD_VERSION }}

      - name: Run cabal-gild
        working-directory: waspc
        run: |
          for f in $(git ls-files '*.cabal'); do
            cabal-gild --mode check --input "$f"
          done
