name: "Test - Publish nightly Wasp npm packages to pkg.pr.new"

on:
  workflow_call:

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version-file: waspc/.nvmrc

        # Tokenless npm publishing requires npm v11.5.1+ so we install it
        # explicitly.
        # Read more: https://docs.npmjs.com/trusted-publishers/
      - name: Install latest npm
        run: npm i -g npm@^11.5.1

      - uses: actions/download-artifact@v6
        with:
          name: ${{ vars.WASP_NPM_ARTIFACT_NAME }}
          path: packages/

      - name: Publish Wasp npm packages
        run: npx pkg-pr-new publish --bin --compact ./packages/*
