name: "Test - Publish nightly Wasp npm packages to pkg.pr.new"

on:
  workflow_call:

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
      # We don't set a specific node version here because we want to use the
      # latest, to get token-less npm publishing.
      # Read more: https://docs.npmjs.com/trusted-publishers/
      - uses: actions/setup-node@v6

      - uses: actions/download-artifact@v6
        with:
          name: ${{ vars.WASP_NPM_ARTIFACT_NAME }}
          path: packages/

      - name: Publish Wasp npm packages
        run: npx pkg-pr-new publish --bin --compact ./packages/*
