name: "Test - TS Spec"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

jobs:
  test-wasp-config:
    name: Test wasp-config
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v6"

      - uses: actions/setup-node@v6
        with:
          node-version-file: waspc/.nvmrc

      - name: Install wasp-config dependencies
        working-directory: waspc/data/packages/wasp-config
        run: npm ci

      - name: Run wasp-config tests
        working-directory: waspc/data/packages/wasp-config
        run: npm run test
