name: "Release - Check, build, and upload binaries"

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-create"
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      override-npm-package-version: ${{ github.ref_name }}

  create-release:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: wasp-cli-*

      # `download-artifact` will download each artifact into its own separate
      # directory. We need to account for this in the glob pattern for the
      # release artifacts. The glob should only include the files inside the
      # folders, not the folders themselves.

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "./wasp-cli-*/*"
          artifactErrorsFailBuild: true
          replacesArtifacts: true

  publish-npm:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - # We don't set a specific node version here because we want to use the
        # latest, to get token-less npm publishing.
        uses: actions/setup-node@v6

      - uses: actions/download-artifact@v6
        with:
          name: wasp-npm-packages
          path: packages/

      - name: Publish Wasp npm packages
        run: |
          set -x # Log each command for debugging
          for pkg in ./packages/*; do
            npm publish "$pkg"
          done
