name: "Release - Check, build, and upload binaries"

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-create"
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      override-npm-package-version: ${{ github.ref_name }}

  create-release:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: wasp-cli-*

      # `download-artifact` will download each artifact into its own separate
      # directory. We need to account for this in the glob pattern for the
      # release artifacts. The glob should only include the files inside the
      # folders, not the folders themselves.

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "./wasp-cli-*/*"
          artifactErrorsFailBuild: true
          replacesArtifacts: true

  publish-npm:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - uses: actions/download-artifact@v6
        with:
          name: ${{ vars.WASP_NPM_ARTIFACT_NAME }}
          path: packages/

      - name: Publish Wasp npm packages
        # Tokenless npm publishing requires npm v11.5.1+ so we request it
        # explicitly.
        # Read more: https://docs.npmjs.com/trusted-publishers/
        run: |
          set -x # Log each command for debugging
          for pkg in ./packages/*; do
            # The tag name has no special meaning, just avoids us
            # broadly publishing an RC to the "latest" tag.
            npx npm@^11.5.1 publish --tag rc "$pkg"
          done
